"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import React, { useState } from "react";
import Navbar from "@/components/NavbarHelper/Navbar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar className="top-2" />
        {children}
      </body>
    </html>
  );
}
